version: '3.8'
services:
  ff-bot:
    build: .
    image: ff-bot
    container_name: ff-bot
    restart: unless-stopped
    volumes:
      - ./token.json:/app/token.json:ro
    working_dir: /app
    command: ["python", "-u", "main.py"]
